#!/bin/sh

REQUIRED_VERSION=1.8
jumpto() {
   echo "Installing oracle java8"
   sudo apt-get install -y python-software-properties debconf-utils
   sudo add-apt-repository -y ppa:webupd8team/java
   sudo apt-get update
   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
   sudo apt-get install -y oracle-java8-installer
   sudo apt-get install oracle-java8-set-default
}

java -version 2> tmp.ver
VERSION=`cat tmp.ver | grep "java version" | awk '{ print substr($3, 2, length($3)-2); }'`
rm tmp.ver
echo "java current version: $VERSION and expected version: $REQUIRED_VERSION"
VERSION=`echo $VERSION | awk '{ print substr($1, 1, 3); }' | sed -e 's;\.;0;g'`
REQUIRED_VERSION=`echo $REQUIRED_VERSION | awk '{ print substr($1, 1, 3); }' | sed -e 's;\.;0;g'`
if [ $VERSION ]
then
        if [ $REQUIRED_VERSION -gt $VERSION ]
        then
                jumpto
        fi
        sudo java -jar /apps/delta/provisioning-1.0-SNAPSHOT.jar > $1 2> /apps/delta/provisioning-1.0.log &
else
   jumpto
   sudo java -jar /apps/delta/provisioning-1.0-SNAPSHOT.jar > $1 2> /apps/delta/provisioning-1.0.log &
fi
